# Generated by Django 3.0.14 on 2021-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210514_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='text',
            field=models.TextField(),
        ),
    ]
