# Generated by Django 3.0.14 on 2021-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210519_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='text',
        ),
        migrations.AddField(
            model_name='tweets',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
