# Generated by Django 3.2.3 on 2021-07-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_tweets_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetlike',
            old_name='tweets',
            new_name='tweet',
        ),
    ]
