# Generated by Django 3.2.3 on 2021-07-27 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0014_rename_tweets_tweetlike_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_like', through='tweets.TweetLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
